spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deviceshop?currentSchema=deviceshop
    username: postgres
    password: 12341234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      #data-locations: classpath:demo_data.sql